// packages/presets/templates/preact-ts/resources/views/components/footer.tsx
// @ts-nocheck
export default function Footer() {
  return (
    <footer>
      <div className="container">
        <p>
          Build with <a href="https://laravel.com/">Laravel</a>,{' '}
          <a href="https://wreathe.dev/">Wreathe</a> &{' '}
          <a href="https://preactjs.com/">Preact</a>
        </p>
      </div>
    </footer>
  )
}

// packages/presets/templates/vue-ts/resources/views/components/footer.vue
<template>
  <footer>
    <div class="container">
      <p>
        build with <a href="https://laravel.com/">Laravel</a>,
        <a href="https://inertiajs.com/">Inertia.js</a>,
        <a href="https://github.com/jrson83/inertia-preact">
          Inertia.js Preact Adapter
        </a>
        & <a href="https://preactjs.com/">Preact</a>
      </p>
    </div>
  </footer>
</template>
