// packages/presets/templates/react-ts/resources/views/pages/example.tsx
// @ts-nocheck
import { Fragment } from 'react'
import { Head } from '@wreathe-js/react'

import Counter from '@/views/components/counter'
import Layout from '@/views/layouts/default'

const Example = () => {
  return (
    <Fragment>
      <Head title="Example" />
      <h1>Counter</h1>
      <p>
        This is a simple, hydrated <code>Counter</code> component.
      </p>
      <Counter />
    </Fragment>
  )
}

Example.layout = (page: Page) => <Layout children={page} />

export default Example

// packages/presets/templates/vue-ts/resources/views/pages/example.vue
<script setup lang="ts">
import { Head as WreatheHead } from '@wreathe-js/vue'
import Counter from '@/views/components/counter.vue'
</script>

<script lang="ts">
import DefaultLayout from '@/views/layouts/default.vue'

export default {
  layout: DefaultLayout,
}
</script>

<template>
  <div>
    <WreatheHead title="Example" />

    <h1>Counter</h1>
    <p>This is a simple, hydrated <code>Counter</code> component.</p>
    <Counter />
  </div>
</template>
